#
# GophKeeper server configuration file
#
# You may use environment variables instead of config file:
# SERVER_PORT - GRPC server port (ex. ':8080')
# DATABASE_DSN - connection string for postgres engine
# TOKENS_SECRETKEY - secret key for access and refresh tokens hashing
# TOKENS_ACCESSTOKENDURATION - access token expiration time
# TOKENS_REFRESHTOKENDURATION - refresh token expiration time

# Tokens configuration
tokens:
  secretKey: "secret key for access tokens hashing"
  accessTokenDuration: "10m"
  refreshTokenDuration: "24h"

# Database configuration
databaseDSN: "postgres://postgres:qwe123@localhost:5432/gophkeeper_dev?sslmode=disable"

# Server configuration
server:
  port: ":3000"
